version: 2
updates:
  # Maintain dependencies for Maven (dev)
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "dev" # Dependabot will check the 'dev' branch
    schedule:
      interval: "daily"
    # Groups updates to reduce PR noise
    groups:
      dev-deps:
        patterns:
          - "*"

  # Maintain dependencies for Maven (prod)
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "prod" # Dependabot will check the 'prod' branch
    schedule:
      interval: "daily"
    # Groups updates to reduce PR noise  
    groups:
      prod-deps:
        patterns:
          - "*"
