version: 2
updates:
  # Maintain dependencies for Gradle (dev)
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "dev" # Dependabot will check the 'dev' branch
    schedule:
      interval: "daily"
    # Groups updates to reduce PR noise
    groups:
      dev-deps:
        patterns:
          - "*"
    ignore:
      # Fully ignore bungeecord-api
      - dependency-name: "net.md-5:bungeecord-api"

      # Only allow 2.x.x updates for async-http-client
      - dependency-name: "org.asynchttpclient:async-http-client"
        versions: [">= 3.0.0"]
      # Only allow 4.x.x updates for kyori adventure api.
      - dependency-name: "org.asynchttpclient:async-http-client"
        versions: [">= 5.0.0"]  
