version: 2
updates:
  # Maintain dependencies for Gradle (dev)
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "dev" # Dependabot will check the 'dev' branch
    schedule:
      interval: "daily"
    # Groups updates to reduce PR noise
    groups:
      dev-deps:
        patterns:
          - "*"
