<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cloud.gteam</groupId>
    <artifactId>CoralGate</artifactId>
    <version>0.3.0-beta</version> <!-- mvn versions:set -DnewVersion=VERSION !-->
    <packaging>pom</packaging>

    <modules>
        <module>core</module>
        <module>spigot</module>
        <module>paper</module>
        <module>bungeecord</module>
        <module>velocity</module>
    </modules>

    <properties>
        <!-- Project related options !-->
        <java.version>1.8</java.version>
        <core.version>0.3.0-beta</core.version>
        <api.version>v2</api.version>

        <!-- Dependencies related options !-->
        <bstats.version>3.2.1</bstats.version>
        <lamp.version>4.0.0-rc.16</lamp.version>
        <packetevents.version>2.12.1</packetevents.version>
    </properties>

</project>
