#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Nov 14 14:50:13 CET 2025
maven-metadata-codemc-releases.xml.error=
maven-metadata-codemc-releases.xml.lastUpdated=1763128213525
maven-metadata-sonatype-nexus-snapshots.xml.error=
maven-metadata-sonatype-nexus-snapshots.xml.lastUpdated=1763128213526
